/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jason
 */
public class BMI_FRAME extends javax.swing.JFrame {
    //Global double for height and weight
    double height, weight;
    /**
     * Creates new form BMI_FRAME
     */
    public BMI_FRAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeightGroup = new javax.swing.ButtonGroup();
        WeightGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        bmi_label = new javax.swing.JLabel();
        cal_btn = new javax.swing.JButton();
        lbheight = new javax.swing.JLabel();
        lbweight = new javax.swing.JLabel();
        RbtHeight1 = new javax.swing.JRadioButton();
        RbtHeight2 = new javax.swing.JRadioButton();
        RbtHeight3 = new javax.swing.JRadioButton();
        RbtWeight1 = new javax.swing.JRadioButton();
        RbtWeight2 = new javax.swing.JRadioButton();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CHeight = new javax.swing.JLabel();
        CWeight = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb1.setForeground(new java.awt.Color(0, 0, 0));
        lb1.setText("Height:");

        lb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb2.setForeground(new java.awt.Color(0, 0, 0));
        lb2.setText("Weight:");

        tf1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tf2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bmi_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bmi_label.setForeground(new java.awt.Color(0, 0, 0));
        bmi_label.setText("Result :");

        cal_btn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cal_btn.setForeground(new java.awt.Color(0, 0, 0));
        cal_btn.setText("CALCULATE");
        cal_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cal_btnMouseClicked(evt);
            }
        });

        lbheight.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbheight.setForeground(new java.awt.Color(0, 0, 0));
        lbheight.setText("Height");

        lbweight.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbweight.setForeground(new java.awt.Color(0, 0, 0));
        lbweight.setText("Weight");

        HeightGroup.add(RbtHeight1);
        RbtHeight1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RbtHeight1.setForeground(new java.awt.Color(0, 0, 0));
        RbtHeight1.setText("Meters (Default)");
        RbtHeight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtHeight1ActionPerformed(evt);
            }
        });

        HeightGroup.add(RbtHeight2);
        RbtHeight2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RbtHeight2.setForeground(new java.awt.Color(0, 0, 0));
        RbtHeight2.setText("Feet");
        RbtHeight2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtHeight2ActionPerformed(evt);
            }
        });

        HeightGroup.add(RbtHeight3);
        RbtHeight3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RbtHeight3.setForeground(new java.awt.Color(0, 0, 0));
        RbtHeight3.setText("Inches");
        RbtHeight3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtHeight3ActionPerformed(evt);
            }
        });

        WeightGroup.add(RbtWeight1);
        RbtWeight1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RbtWeight1.setForeground(new java.awt.Color(0, 0, 0));
        RbtWeight1.setText("Kilograms (Default)");
        RbtWeight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtWeight1ActionPerformed(evt);
            }
        });

        WeightGroup.add(RbtWeight2);
        RbtWeight2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RbtWeight2.setForeground(new java.awt.Color(0, 0, 0));
        RbtWeight2.setText("Pounds");
        RbtWeight2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtWeight2ActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setText("BMI Calculator");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Enter your height and weight then choose your measurement.");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("It will automatically convert it into meters and kilograms for calculation.");

        CHeight.setForeground(new java.awt.Color(0, 0, 0));
        CHeight.setText("Current Height -");

        CWeight.setForeground(new java.awt.Color(0, 0, 0));
        CWeight.setText("Current Weight -");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Title)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cal_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bmi_label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CWeight, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CHeight, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb2)
                                            .addComponent(lb1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tf2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RbtHeight2)
                                            .addComponent(RbtHeight1)
                                            .addComponent(lbheight))
                                        .addGap(82, 82, 82)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RbtWeight1)
                                            .addComponent(lbweight)
                                            .addComponent(RbtWeight2))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(RbtHeight3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbheight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RbtHeight1)
                        .addGap(18, 18, 18)
                        .addComponent(RbtHeight2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbweight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RbtWeight1)
                        .addGap(18, 18, 18)
                        .addComponent(RbtWeight2)))
                .addGap(18, 18, 18)
                .addComponent(RbtHeight3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CHeight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CWeight)
                .addGap(18, 18, 18)
                .addComponent(bmi_label)
                .addGap(18, 18, 18)
                .addComponent(cal_btn)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cal_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cal_btnMouseClicked
        if (height == 0.0 || weight == 0.0){
            //If radiobutton is not selected it will be default
            height = Double.parseDouble(tf1.getText());
            weight = Double.parseDouble(tf2.getText());
        }
        
        double bmi = weight / (height * height);
        
        if (bmi < 18.5)
        bmi_label.setText("Result: underweight - BMI : " + bmi);
        else if (bmi < 25)
        bmi_label.setText("Result: normal - BMI : " + bmi);
        else if (bmi < 30)
        bmi_label.setText("Result: overweight - BMI : " + bmi);
        else
        bmi_label.setText("Result: obese - BMI : " + bmi);
        
        //Complete Reset
        HeightGroup.clearSelection();
        WeightGroup.clearSelection();
        tf1.setText("");
        tf2.setText("");
        CHeight.setText("Current Height - ");
        CWeight.setText("Current Weight - ");
        weight = 0.0;
        height = 0.0;
    }//GEN-LAST:event_cal_btnMouseClicked

    private void RbtWeight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtWeight2ActionPerformed
        // TODO add your handling code here:
        //Pounds to Kilograms
        weight = Double.parseDouble(tf2.getText()) * 0.45359237;
        CWeight.setText("Current Weight - " + weight);
        bmi_label.setText("Result:");
    }//GEN-LAST:event_RbtWeight2ActionPerformed

    private void RbtHeight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtHeight1ActionPerformed
        // TODO add your handling code here:
        //Default Meters
        height = Double.parseDouble(tf1.getText());
        CHeight.setText("Current Height - " + height);
        bmi_label.setText("Result:");
    }//GEN-LAST:event_RbtHeight1ActionPerformed

    private void RbtWeight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtWeight1ActionPerformed
        // TODO add your handling code here:
        //Default Kilograms
        weight = Double.parseDouble(tf2.getText());
        CWeight.setText("Current Weight - " + weight);
        bmi_label.setText("Result:");
    }//GEN-LAST:event_RbtWeight1ActionPerformed

    private void RbtHeight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtHeight2ActionPerformed
        // TODO add your handling code here:
        //Feet to Meters
        height = Double.parseDouble(tf1.getText()) * 0.3048;
        CHeight.setText("Current Height - " + height);
        bmi_label.setText("Result:");
    }//GEN-LAST:event_RbtHeight2ActionPerformed

    private void RbtHeight3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtHeight3ActionPerformed
        // TODO add your handling code here:
        //Inches to Meters
        height = Double.parseDouble(tf1.getText()) * 0.0254;
        CHeight.setText("Current Height - " + height);
        bmi_label.setText("Result:");
    }//GEN-LAST:event_RbtHeight3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMI_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMI_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMI_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMI_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMI_FRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CHeight;
    private javax.swing.JLabel CWeight;
    private javax.swing.ButtonGroup HeightGroup;
    private javax.swing.JRadioButton RbtHeight1;
    private javax.swing.JRadioButton RbtHeight2;
    private javax.swing.JRadioButton RbtHeight3;
    private javax.swing.JRadioButton RbtWeight1;
    private javax.swing.JRadioButton RbtWeight2;
    private javax.swing.JLabel Title;
    private javax.swing.ButtonGroup WeightGroup;
    private javax.swing.JLabel bmi_label;
    private javax.swing.JButton cal_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbheight;
    private javax.swing.JLabel lbweight;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
